### ISSUE TITLE
gcn

### ISSUE THREAD

**Issue by liugl7** [marekjg/glore#1]
In the code, GCN only use two ‘nn.Conv1d’.     In the original paper, \mathbf{Z}=G V W_{g}=\left(\left(I-A_{g}\right) V\right) W_{g}  , but not ​​​​​​​​​​​​\mathbf{Z}=G V W_{g}= A_{g} V W_{g}

**Comment by marekjg** [comment]
Apparently, I've used equation from figure 3 for some reason instead of figure 2. However, you can always define A' = I - A and learn A' instead of A. It might impact the optimization capabilities though, as the paper mentions:

> The identity matrix serves as a shortcut connection that al-
leviates  the  optimization  difficulties.

**Comment by liugl7** [comment]
Ok, I see. Thank you

**Comment by xiaoerlaigeid** [comment]
> Apparently, I've used equation from figure 3 for some reason instead of figure 2. However, you can always define A' = I - A and learn A' instead of A. It might impact the optimization capabilities though, as the paper mentions:
> 
> > The identity matrix serves as a shortcut connection that al-
> > leviates  the  optimization  difficulties.

I wonder which implementation has better performance ? have you done some experiments on this?
